apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubegres.yaml

secretGenerator:
  - name: postgres
    envs:
      - secret-params.env

generatorOptions:
  disableNameSuffixHash: true
