apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlbot
  template:
    metadata:
      labels:
        app: sqlbot
    spec:
      containers:
        - name: sqlbot
          image: edwardlol/sqlbot:latest
          args:
            - --host
            - "0.0.0.0"
            - --port
            - "8080"
          envFrom:
            - configMapRef:
                name: sqlbot
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1"
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
