CREATE TABLE ids_day_indicator (
  id int primary key,
  city_code text comment '城市编号',
  merchant_id bigint comment '商户编码',
  exec_date date comment '考勤日期',
  route_id bigint comment '线路编码',
  sub_route_id bigint comment '子线路编码',
  total_plan_seq_num int comment '计划总班次数',
  total_plan_up_seq_num int comment '上行计划总班次数',
  total_plan_down_seq_num int comment '下行计划总班次数',
  total_complete_seq_num double precision comment '实际总班次数',
  total_up_complete_seq_num double precision comment '上行实际总班次数',
  total_down_complete_seq_num double precision comment '下行实际总班次数',
  total_complete_seq_num_part double precision comment '带有分区的总班次数',
  total_operation_mile double precision comment '总营运里程',
  total_up_operation_mile double precision comment '上行总营运里程',
  total_down_operation_mile double precision comment '下行总营运里程',
  total_un_operation_mile double precision comment '总非营运里程',
  total_chartered_mile double precision comment '定制里程',
  total_complete_mile double precision comment '总里程(营运+非营运)',
  passenger_count bigint comment '营运班次客流数',
  rating_passenger_count bigint comment '额定载客数',
  real_operation_second int comment '实际营运时间(单位:秒)',
  real_up_operation_second int comment '上行实际营运时间(单位:秒)',
  real_down_operation_second int comment '下行实际营运时间(单位:秒)',
  plan_operation_second int comment '计划营运时间(单位:秒)',
  plan_up_operation_second int comment '上行计划营运时间(单位:秒)',
  plan_down_operation_second int comment '下行计划营运时间(单位:秒)',
  operation_time_sum int comment '完成营运班次时间(单位:秒)',
  operation_down_time_sum int comment '完成下行营运班次时间(单位:秒)',
  operation_up_time_sum int comment '实际上行营运班次时间(单位:秒)',
  first_schedule_seq_num int comment '首班正点班次',
  first_early_seq_num int comment '首班早点班次',
  first_late_seq_num int comment '首班晚点班次'
);
